server:
  port: 8082

spring:
  application:
    name: vm-service
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
