server:
  port: 8085
spring:
  application:
    name: vm-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service.discovery.svc.cluster.local:8761/eureka/

  datasource:
    url: jdbc:mysql://mysql.user.svc.cluster.local:3306/ceph_vm_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
