apiVersion: v1
kind: Pod
metadata:
  name: {{CLUSTER_NAME}}-{{ROLE}}-{{USERNAME}}
  labels:
    app: k8s-cluster
    role: {{ROLE}}
spec:
  containers:
    - name: {{ROLE}}
      image: {{IMAGE}}
      resources:
        requests:
          cpu: {{CPU}}
          memory: {{MEMORY}}
        limits:
          cpu: {{CPU}}
          memory: {{MEMORY}}
